services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DATABASE_URI=mongodb://127.0.0.1:27017/test
      - SECRET=secret
    depends_on:
      - mysql

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
